export const strings = {
  defaultName: 'Default Name',
  defaultNumber: '01234567890',
  defaultPlaceholder: 'Default Placeholder',
  defaultTitle: 'Default Title',
  noAccTxt: "Don't have an account?",
  haveAcc: 'Already have an account?',
  signupTxt: 'Sign up!',
  loginTxt: 'Login!',
  username: 'Username',
  password: 'Passowrd',
  login: 'Login',
  signup: 'Sign Up',
  addtofav: 'Add to favorites',
};
